sudo: required
language: python
jdk: openjdk8
services: docker
python: '3.6'
cache: pip
matrix:
  fast_finish: true

before_install:
  # PRs to master are only ok if coming from dev branch
  - '[ $TRAVIS_PULL_REQUEST = "false" ] || [ $TRAVIS_BRANCH != "master" ] || ([ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ] && ([ $TRAVIS_PULL_REQUEST_BRANCH = "dev" ] || [ $TRAVIS_PULL_REQUEST_BRANCH = "patch" ]))'
  # Pull the docker image first so the test doesn't wait for this
  - docker pull nfcore/eager:dev
  # Fake the tag locally so that the pipeline runs properly
  # Looks weird when this is :dev to :dev, but makes sense when testing code for a release (:dev to :1.0.1)
  - docker tag nfcore/eager:dev nfcore/eager:dev

install:
  # Install Nextflow
  - mkdir /tmp/nextflow && cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Install nf-core/tools
  - pip install --upgrade pip
  - pip install nf-core
  # Install Conda 
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -f -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # Reset
  - mkdir ${TRAVIS_BUILD_DIR}/tests && cd ${TRAVIS_BUILD_DIR}/tests
  # Install markdownlint-cli
  - sudo apt-get install npm && npm install -g markdownlint-cli


env:
   global:
  # https://tower.nf/ with email nf-core@mailinator.com
  # Tower login mailbox: https://www.mailinator.com/v3/index.jsp?zone=public&query=nf-core
  - TOWER_ACCESS_TOKEN=1c1f493bc2703472d6f1b9f6fb9e9d117abab7b1
  - JOBNAME="eager-${TRAVIS_PULL_REQUEST_BRANCH}_${TRAVIS_COMMIT:0:6}_${TRAVIS_BUILD_NUMBER}.${TRAVIS_JOB_ID}"
  # Copying from Phil, remove ANSI as bugs out on travis
  - NXF_ANSI_LOG=0

  jobs:
  - NXF_VER='19.04.0' # Specify a minimum NF version that should be tested and work
  - NXF_VER='' # Plus: get the latest NF version and check that it works

script:
  # Lint the pipeline code
  - nf-core lint ${TRAVIS_BUILD_DIR}
  # REFERENCE: Run the basic pipeline with the test profile
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-basic" -with-tower -profile test,docker --pairedEnd --saveReference
  # REFERENCE: Run the basic pipeline with single end data (pretending its single end actually) and all prepared index files
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-singleEnd" -with-tower -profile test,docker --singleEnd 
  # REFERENCE: Run the basic pipeline with FastA reference with `fna` extension
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-fna_ref" -with-tower -profile test_fna,docker --pairedEnd --saveReference
  # REFERENCE: Test using pre-computed indices from a separate run beforehand
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-preindex_ref" -with-tower -profile test_fna,docker --pairedEnd --bwa_index results/reference_genome/bwa_index/BWAIndex/Mammoth_MT_Krause.fna --fasta_index results/reference_genome/fasta_index/Mammoth_MT_Krause.fna.fai --seq_dict results/reference_genome/seq_dict/Mammoth_MT_Krause.dict 
  # REFERENCE: Test with zipped reference input
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-gz_ref" -with-tower -profile test,docker --pairedEnd --fasta 'https://github.com/nf-core/test-datasets/raw/eager/reference/Mammoth/Mammoth_MT_Krause.fasta.gz'
  # FASTP: Run the same pipeline testing optional step: fastp, complexity 
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-fastp" -with-tower -profile test,docker --pairedEnd --complexity_filter
  # ADAPTERREMOVAL: Run the basic pipeline with paired end data without collapsing
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-skip_collapse" -with-tower -profile test,docker --pairedEnd --skip_collapse
  # ADAPTERREMOVAL: Run the basic pipeline with paired end data without trimming, but still merge
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-pretrim" -with-tower -profile test_pretrim,docker --pairedEnd --skip_trim 
  # ADAPTERREMOVAL: Run the basic pipeline with paired end data without adapterRemoval
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-skip_adapterremoval" -with-tower -profile test,docker --pairedEnd --skip_adapterremoval
  # ADAPTERREMOVAL: Run the basic pipeline with preserve5p end option
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-preserve5p" -with-tower -profile test,docker --pairedEnd --preserve5p
  # ADAPTERREMOVAL: Run the basic pipeline with merged only option
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-mergedonly" -with-tower -profile test,docker --pairedEnd --mergedonly
  # ADAPTERREMOVAL: Run the basic pipeline with preserve5p end and merged reads only options
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-preserve5p_mergedonly" -with-tower -profile test,docker --pairedEnd --preserve5p --mergedonly
  # MAPPER_CIRCULARMAPPER: Test running with CircularMapper
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-circularmapper" -with-tower -profile test,docker --pairedEnd --mapper 'circularmapper' --circulartarget 'NC_007596.2'
  # MAPPER_BWAMEM: Test running with BWA Mem
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-bwa_mem" -with-tower -profile test,docker --pairedEnd --mapper 'bwamem'
  # STRIP_FASTQ: Run the basic pipeline with output unmapped reads as fastq
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-stripfastq" -with-tower -profile test,docker --pairedEnd --strip_input_fastq
  # BAM_FILTERING: Run basic mapping pipeline with mapping quality filtering, and unmapped export
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-unmapped_export" -with-tower -profile test,docker --pairedEnd --run_bam_filtering --bam_mapping_quality_threshold 37 --bam_discard_umapped --bam_unmapped_type 'fastq'
  # GENOTYPING_HC: Test running GATK HaplotypeCaller
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-haplotypercaller" -with-tower -profile test_fna,docker --pairedEnd  --dedupper 'dedup' --run_genotyping --genotyping_tool 'hc' --gatk_out_mode 'EMIT_ALL_SITES' --gatk_hc_emitrefconf 'BP_RESOLUTION'
  # GENOTYPING_FB: Test running FreeBayes
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-freebayes" -with-tower -profile test,docker --pairedEnd  --dedupper 'dedup' --run_genotyping --genotyping_tool 'freebayes'
  # SKIPPING: Test checking all skip steps work i.e. input bam, skipping straight to genotyping
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-skipping_logic" -with-tower -profile test_bam,docker --bam --singleEnd --skip_fastqc --skip_adapterremoval --skip_mapping --skip_deduplication --skip_qualimap --skip_preseq --skip_damage_calculation --run_genotyping --genotyping_tool 'freebayes'
  # TRIM_BAM/PMD/GENOTYPING_UG/MULTIVCFANALYZER: Test running PMDTools, TrimBam, GATK UnifiedGenotyper and MultiVCFAnalyzer
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-pmd_trimbam_unifiedgenotyper_multivcfanalyzer" -with-tower -profile test,docker --pairedEnd  --dedupper 'dedup' --run_trim_bam --run_pmdtools --run_genotyping --genotyping_source 'trimmed' --genotyping_tool 'ug' --gatk_out_mode 'EMIT_ALL_SITES' --gatk_ug_genotype_model 'SNP' --run_multivcfanalyzer
  # GENOTYPING_UG/PMD/MULTIVCFANALYZER: Test running GATK UnifiedGenotyper and MultiVCFAnalyzer, additional VCFS
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-multivcfanalyzer_additionalvcfs" -with-tower -profile test,docker --pairedEnd  --dedupper 'dedup' --run_genotyping --genotyping_tool 'ug' --gatk_out_mode 'EMIT_ALL_SITES' --gatk_ug_genotype_model 'SNP' --run_multivcfanalyzer --additional_vcf_files 'https://raw.githubusercontent.com/nf-core/test-datasets/eager/testdata/Mammoth/vcf/JK2772_CATCAGTGAGTAGA_L008_R1_001.fastq.gz.tengrand.fq.combined.fq.mapped_rmdup.bam.unifiedgenotyper.vcf.gz' --write_allele_frequencies
  # BEDTOOLS: Run basic pipeline but get additional feature coverage stats
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-bedtools" -with-tower -profile test,docker --pairedEnd --run_bedtools_coverage --anno_file "https://raw.githubusercontent.com/nf-core/test-datasets/eager/reference/Mammoth/Mammoth_MT_Krause.gff3"
  # BAM_INPUT: Run the basic pipeline with the bam input profile, skip AdapterRemoval as no convertBam
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-baminput_noConvertBam" -with-tower -profile test_bam,docker --bam --skip_adapterremoval --run_convertbam
  # BAM_INPUT: Run the basic pipeline with the bam input profile, convert to FASTQ for adapterremoval test and downstream
  - nextflow run ${TRAVIS_BUILD_DIR} -name "${JOBNAME}-baminput_convertbam_basic" -with-tower -profile test_bam,docker --bam --run_convertbam
  # [DISABLED UNTIL BED FILE AVAILABLE - 2h RUN TIME WITHOUT] - SEXDETERMINAION: Run the basic pipeline with the bam input profile, but don't convert BAM, skip everything but sex determination
  #- nextflow run ${TRAVIS_BUILD_DIR} -with-tower -profile test_humanbam,docker --bam --skip_fastqc --skip_adapterremoval --skip_mapping --skip_deduplication --skip_qualimap --singleEnd --run_sexdeterrmine
  # [DISABLED UNTIL SMALL HUMAN REFERENCE AVALIABLE - REQUIRES HUMAN FASTA] - NUCLEAR INPUT
  #- nextflow run ${TRAVIS_BUILD_DIR} -with-tower -profile test_humanbam,docker --bam --skip_fastqc --skip_adapterremoval --skip_mapping --skip_deduplication --skip_qualimap --singleEnd --run_nuclearcontamination

